language: node_js
node_js:
  - "node"
  - "stable"
  - "10.14.2"

cache:
  directories: 
    - "node_modules"
before_install:
  - "npm install"

after_success: 
  - "npm run coveralls"
  - "npm run coverage"
script:
  - "npm run test"
  - "- ./cc-test-reporter after-build -r --exit-code $TRAVIS_TEST_RESULT"
  