language: node_js
node_js:
  - "node"
  - "stable"

cache:
  directories: 
    - "node_modules"
before_install:
  - "npm install"
  - "npm install mocha nyc istanbul"

after_success: 
  - "npm run coveralls"
  - "npm run coverage"
  